[package]
name = "timelapse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17"
chrono = "0.4"
anyhow = "1.0"
ctrlc = "3.4"
